# -*- coding: utf-8 -*-
"""NLP_practicals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QrujZFCcezTxceP09KxQ0e1k-LoGI5gz

#Practical 5

**Important NLP Libraries for Indian Languages and perform:**

**a. Word tokenization in Hindi language**
"""

!pip install inltk

from inltk.inltk import setup
setup('hi') #download hindi file

print("53004200003 Alicia Cotta")
from inltk.inltk import tokenize

hindi_text = """प्राचीन काल में विक्रमादित्य नाम का एक आदर्श राजा हुआ करता था। राजा विक्रम अपने साहस, पराक्रम और पराक्रम के लिए प्रसिद्ध थे। यह भी कहा जाता है कि राजा विक्रम अपनी प्रजा के जीवन के दुख-दर्द को जानने के लिए रात के तड़के वेश में शहर में घूमते थे। और पीड़ितों के दुख को भी दूर करते थे।"""

# tokenize(input text, language code)
tokenize(hindi_text, "hi")

"""**b. Generate similar sentences from a given Hindi text input**"""

!pip install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

!pip install tornado==4.5.3

from inltk.inltk import setup
setup('hi')

print("53004200003 Alicia Cotta")
#import warnings
#warnings.filterwarnings('ignore')
from inltk.inltk import get_similar_sentences

# get similar sentences to the one given in hindi
output = get_similar_sentences('मैं आज बहुत खुश हूं', 5, 'hi')

print(output)

"""**c. Identify the Indian language of a text**"""

!pip install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

!pip install tornado==4.5.3

print("53004200003 Alicia Cotta")
#import warnings
#warnings.filterwarnings('ignore')
from inltk.inltk import identify_language
#Identify the Lnaguage of given text
identify_language('मी विद्यार्थी आहे')
